unbind r
bind r source-file ~/.tmux.conf

bind C-p previous-window
bind C-n next-window

set -g prefix C-s
set -g base-index 1

bind-key -n PgUp copy-mode -u
bind-key -T copy-mode PgUp send-keys -X page-up
bind-key -T copy-mode PgDn send-keys -X page-down

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-bg "#33b1ff"

run '~/.tmux/plugins/tpm/tpm'
